server:
  port: 7969
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${VPS_HOST:localhost}:3306/openApi
    username: oreki
    password: ${PASSWORD}
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: ${VPS_HOST:localhost}
    port: 6379
    timeout: 5000
    password: ${PASSWORD}
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://${VPS_HOST:localhost}:9200
    username: root
    password: ${PASSWORD}